name: cypress tests
on: [push]
jobs:
  cypress-smoke-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: setup npm package
        run: 
              npm ci
              $(npm bin)/cypress cache path
              $(npm bin)/cypress cache list
              $(npm bin)/cypress verify   

      - name: run test scripts
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm run cypress:headless
        continue-on-error: true

      - name: generate the HTML Report
        run: node .//cypress//htmlreport.js

      - name: copy reports to public folder
        run: |
          mkdir public
          # cp -r cypress/screenshots public/screenshots
          # cp -r cypress/videos public/videos
          cp -r ./reports/ public/report
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
