name: cypress tests
on: [push]

jobs:
 cypress-tests-ui:
   runs-on: ubuntu-latest
   
   strategy:
    matrix:
      node-version: [16.x]

   steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
       node-version: ${{ matrix.node-version }}    '
      
    - name: npm package and project setup
    - run: npm i -g lerna
    - run: yarn bootstrap

    - name: run test scripts
      uses: cypress-io/github-action@v4
      with:
       start: npm run ui:test
       continue-on-error: true
          
    - name: generate the HTML Report
      run: node ./cypress/htmlreport.js

    - name: upload report
      uses: actions/upload-artifact@v3.0.0
      with:
       name: cypress-cucumber-report
       path: ./cypress/ui-htmlreports/
