name: cypress tests
on: [push]
jobs:
  cypress-smoke-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: setup npm package
        run: npm ci
      - name: run test scripts
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npx cypress run
        continue-on-error: true

      - name: generate the HTML Report
        run: node .//cypress//htmlreport.js
      
      - name: upload report
        uses: actions/upload-artifact@v3.0.0
        with:
          name: cypress-cucumber-report
          path: ./reports/