name: cypress tests
on: [push]

jobs:
 cypress-tests-ui:
   runs-on: windows-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup node.js environment
      uses: actions/setup-node@v3
      
    - run: npm i -g lerna
    - run: yarn bootstrap

    - name: run test scripts
      uses: cypress-io/github-action@v4
      with:
       start: npm run ui:test
       continue-on-error: true
          
    - name: generate the HTML Report
      run: node ./cypress/htmlreport.js

    - name: upload report
      uses: actions/upload-artifact@v3.0.0
      with:
       name: cypress-cucumber-report
       path: ./cypress/ui-htmlreports/
