name: cypress tests
on: [push]
jobs:
  cypress-smoke-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup npm package
        run: npm i -g yarn
      - name: running bootstrap command
        run: yarn bootstrap
      - name: run test scripts
        uses: cypress-io/github-action@v4
        with:
          start: npm run cypress:headless
          continue-on-error: true

      - name: generate the HTML Report
        run: node .//cypress//htmlreport.js
      
      - name: upload report
        uses: actions/upload-artifact@v3.0.0
        with:
          name: cypress-cucumber-report
          path: ./reports/
